### PR TITLE
Update mexjulia.cpp

### PR DESCRIPTION
**Pull request by maartenvd**
turn of options handling juliamatlab@3a5140a

It greatly increased stability, though I don't know why. Your fork is the most up to date one, are there plans of making this the main branch?

### CODE REVIEW

**Comment by jebej** [comment]
Thanks for the PR!

In a later commit, this particular change was reverted: https://github.com/juliamatlab/mexjulia/commit/9116929753556fb957f350258659cd973629e0ef

What OS are you on, and for what operations do you notice improvements with this change?

Regarding the main branch question, I think it is simpler for now to leave the situation as-is. Eventually if this package is stable enough it could be moved to JuliaInterop.

**Comment by maartenvd** [comment]
I suffered from segfaults (ubuntu 18.04, matlab r2018a, julia 1.5.1) and it was difficult to pinpoint where they came from. I have a setup.m and setup.jl file;

```
function setup()

addpath(genpath(pwd));

jl.eval();
jl.include('setup.jl');
end
```

```
using TensorKit;
...
```

without the patch, setup.m always causes matlab to crash. With the patch, if I uncomment jl.eval(), it still crashes, but with jl.eval() first, it doesn't.

If my packages still need to precompile, then it also still appears to crash.

Maybe I did something wrong that makes it this unstable?

**Comment by maartenvd** [comment]
Ah wait, I am supposed to call jl.init(), and the reason it sometimes still worked was because jl.call automatically calls jl.init?

**Comment by jebej** [comment]
Both `jl.call` and `jl.eval` automatically call `jl.init`, but you made me notice that `jl.include` doesn't, so that was probably the issue. I'll fix that.

**Comment by jebej** [comment]
Ok, try pulling the latest master and try things out.

I know things aren't super stable, I think there are still issues if an error occurs in julia in certain cases.

**Comment by maartenvd** [comment]
I still find that turning off signals improves stability here, but I now investigated it a bit better. Matlab on it's own (-nodisplay) works just fine either way, but as soon as I try to use the gui, I get crashes without a stacktrace after having the editor open for some time. I can try to pinpoint it further, but I suspect the jvm https://discourse.julialang.org/t/using-julia-from-the-jvm-clojure/51052/10

**Comment by maartenvd** [comment]
I'm not sure how to debug this further, gdb quits with a segfault and empty stacktrace. Are you on linux - and if so, can you replicate it? If not, what matlab version are you on?

**Comment by jebej** [comment]
So it crashes even with the signals off? Does it work at all with signal on?

I am on windows, and things are generally fine (as long as no errors occur in julia code). I have been using this package for about a year now without issues.

**Comment by maartenvd** [comment]
With signals off I have a pretty stable experience (modulo problems when julia errors, but even that mostly works), problems appear when not turning signals off. However matlab with -nojvm works just fine, it is only when also using the matlab gui that I get crashes. 

I assumed this was the issue : https://github.com/cnuernber/libjulia-clj/blob/84f74e7d15292bc795e96653608ab2e4b29f0b99/topics/signals.md but then I don't understand why that commit was reversed. If you want I can try it out on windows as well.

I can record matlab segfaulting with some screencapture software, but I don't know how to get an actual useable stacktrace using gdb. I can also try to edit the signal handling code in julia and sprinkle in some printf's to make sure thats where it goes awry, but to be frank I don't understand that bit of code at all.

**Comment by NBoulle** [comment]
Hi, I had the same issue than @maartenvd a while ago which was also solved by turning the signals off (see https://github.com/NBoulle/Mex.jl/commit/dabcddc56c4b00ed2bc2de17e742e3d76c341020)
and also have those when I use the master branch of your fork. 
Using this patch seems to work fine (I'm on Ubuntu 20.04 with MATLAB R2020b).

By the way, thanks for updating this package, it's very useful :)

**Comment by jebej** [comment]
Understood, let's try it then. Hopefully it doesn't make things worse elsewhere.

**Pull request merged**
